---
title: "Jeff's Journal - Declaration of Existence"
description: |
  Existence Proclamation.
author:
  - name: Jeff Asselin
    url: https://jeffreyasselin.netlify.app/declaration_of_existence
date: 02-02-2021
output:
  distill::distill_article:
    self_contained: false
---

Hi, my name is Jeff Asselin. I currently work as a data analyst at a company called TechTarget, based out of Newton, Massachusetts.

I wanted to start a blog mostly because I am tired of (read: inspired by) reading a ton of awesome content on other data blogs; I want to showcase what I have learned (both academically and by messier means), particularly in areas beyond my core competencies, and collaborate with other data practitioners wherever and whenever possible (reach out to me on Twitter if you are looking to collab!). Lastly, my hope is that by sharing my work I can help or inspire others following a similar journey. 

As a means of putting my goals and aspirations out into the world, I am planning to write about some sports analytics R projects, scripts, processes, and models I have developed. I am also hoping to write about data explorations in the areas of music, books, and pop culture, and possibly share things like book, movie, and TV reviews if I feel inspired. 

Lastly, this blog was created and will be maintained using RStudio and the distill R package, thank you to RStudio, the maintainers of distill, and the open-source community. 



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```